# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\References\MBFileRefAdvanced\ReferencingSampleUI2.ui'
#
# Created: Mon Feb 05 16:05:15 2018
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ReferencingSample(object):
    def setupUi(self, ReferencingSample):
        ReferencingSample.setObjectName("ReferencingSample")
        ReferencingSample.resize(853, 653)
        self.verticalLayout = QtWidgets.QVBoxLayout(ReferencingSample)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(ReferencingSample)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiEditFilePath = QtWidgets.QLineEdit(self.groupBox)
        self.uiEditFilePath.setObjectName("uiEditFilePath")
        self.horizontalLayout.addWidget(self.uiEditFilePath)
        self.uiBtnBrowsePath = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiBtnBrowsePath.sizePolicy().hasHeightForWidth())
        self.uiBtnBrowsePath.setSizePolicy(sizePolicy)
        self.uiBtnBrowsePath.setMaximumSize(QtCore.QSize(23, 16777215))
        self.uiBtnBrowsePath.setAutoDefault(False)
        self.uiBtnBrowsePath.setObjectName("uiBtnBrowsePath")
        self.horizontalLayout.addWidget(self.uiBtnBrowsePath)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.uiSpinLoadTimes = QtWidgets.QSpinBox(self.groupBox)
        self.uiSpinLoadTimes.setEnabled(False)
        self.uiSpinLoadTimes.setMinimum(1)
        self.uiSpinLoadTimes.setMaximum(999)
        self.uiSpinLoadTimes.setProperty("value", 1)
        self.uiSpinLoadTimes.setObjectName("uiSpinLoadTimes")
        self.horizontalLayout.addWidget(self.uiSpinLoadTimes)
        self.uiBtnLoad = QtWidgets.QPushButton(self.groupBox)
        self.uiBtnLoad.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiBtnLoad.sizePolicy().hasHeightForWidth())
        self.uiBtnLoad.setSizePolicy(sizePolicy)
        self.uiBtnLoad.setMaximumSize(QtCore.QSize(50, 16777215))
        self.uiBtnLoad.setObjectName("uiBtnLoad")
        self.horizontalLayout.addWidget(self.uiBtnLoad)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(ReferencingSample)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.uiTableNamespace = QtWidgets.QTableView(self.groupBox_2)
        self.uiTableNamespace.setMinimumSize(QtCore.QSize(400, 0))
        self.uiTableNamespace.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.uiTableNamespace.setTabKeyNavigation(False)
        self.uiTableNamespace.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.uiTableNamespace.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.uiTableNamespace.setObjectName("uiTableNamespace")
        self.uiTableNamespace.horizontalHeader().setHighlightSections(False)
        self.uiTableNamespace.horizontalHeader().setSortIndicatorShown(False)
        self.uiTableNamespace.horizontalHeader().setStretchLastSection(True)
        self.uiTableNamespace.verticalHeader().setVisible(True)
        self.uiTableNamespace.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_3.addWidget(self.uiTableNamespace)
        self.uiTreeNamespace = QtWidgets.QTreeWidget(self.groupBox_2)
        self.uiTreeNamespace.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.uiTreeNamespace.setAlternatingRowColors(True)
        self.uiTreeNamespace.setObjectName("uiTreeNamespace")
        self.uiTreeNamespace.header().setCascadingSectionResizes(False)
        self.uiTreeNamespace.header().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.uiTreeNamespace)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.uiBtnUnload = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiBtnUnload.sizePolicy().hasHeightForWidth())
        self.uiBtnUnload.setSizePolicy(sizePolicy)
        self.uiBtnUnload.setMinimumSize(QtCore.QSize(130, 0))
        self.uiBtnUnload.setMaximumSize(QtCore.QSize(130, 16777215))
        self.uiBtnUnload.setCheckable(False)
        self.uiBtnUnload.setObjectName("uiBtnUnload")
        self.verticalLayout_2.addWidget(self.uiBtnUnload)
        self.uiBtnReload = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiBtnReload.sizePolicy().hasHeightForWidth())
        self.uiBtnReload.setSizePolicy(sizePolicy)
        self.uiBtnReload.setMinimumSize(QtCore.QSize(130, 0))
        self.uiBtnReload.setMaximumSize(QtCore.QSize(130, 16777215))
        self.uiBtnReload.setCheckable(False)
        self.uiBtnReload.setObjectName("uiBtnReload")
        self.verticalLayout_2.addWidget(self.uiBtnReload)
        self.uiBtnDelete = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiBtnDelete.sizePolicy().hasHeightForWidth())
        self.uiBtnDelete.setSizePolicy(sizePolicy)
        self.uiBtnDelete.setMinimumSize(QtCore.QSize(130, 0))
        self.uiBtnDelete.setMaximumSize(QtCore.QSize(130, 16777215))
        self.uiBtnDelete.setCheckable(False)
        self.uiBtnDelete.setObjectName("uiBtnDelete")
        self.verticalLayout_2.addWidget(self.uiBtnDelete)
        spacerItem1 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        spacerItem2 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uiSpinInstanceTimes = QtWidgets.QSpinBox(self.groupBox_3)
        self.uiSpinInstanceTimes.setMinimum(1)
        self.uiSpinInstanceTimes.setMaximum(999)
        self.uiSpinInstanceTimes.setProperty("value", 1)
        self.uiSpinInstanceTimes.setObjectName("uiSpinInstanceTimes")
        self.horizontalLayout_2.addWidget(self.uiSpinInstanceTimes)
        self.uiBtnInstance = QtWidgets.QPushButton(self.groupBox_3)
        self.uiBtnInstance.setObjectName("uiBtnInstance")
        self.horizontalLayout_2.addWidget(self.uiBtnInstance)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.line_3 = QtWidgets.QFrame(self.groupBox_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.uiBtnRestore = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiBtnRestore.sizePolicy().hasHeightForWidth())
        self.uiBtnRestore.setSizePolicy(sizePolicy)
        self.uiBtnRestore.setMinimumSize(QtCore.QSize(130, 0))
        self.uiBtnRestore.setMaximumSize(QtCore.QSize(120, 16777215))
        self.uiBtnRestore.setCheckable(False)
        self.uiBtnRestore.setObjectName("uiBtnRestore")
        self.verticalLayout_2.addWidget(self.uiBtnRestore)
        spacerItem5 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem5)
        self.uiBtnRestoreShaders = QtWidgets.QPushButton(self.groupBox_3)
        self.uiBtnRestoreShaders.setObjectName("uiBtnRestoreShaders")
        self.verticalLayout_2.addWidget(self.uiBtnRestoreShaders)
        spacerItem6 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem6)
        self.uiBtnBakeShaders = QtWidgets.QPushButton(self.groupBox_3)
        self.uiBtnBakeShaders.setObjectName("uiBtnBakeShaders")
        self.verticalLayout_2.addWidget(self.uiBtnBakeShaders)
        spacerItem7 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem7)
        self.line_2 = QtWidgets.QFrame(self.groupBox_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem8)
        self.uiBtnShowEdits = QtWidgets.QPushButton(self.groupBox_3)
        self.uiBtnShowEdits.setCheckable(False)
        self.uiBtnShowEdits.setObjectName("uiBtnShowEdits")
        self.verticalLayout_2.addWidget(self.uiBtnShowEdits)
        spacerItem9 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem9)
        self.uiBtnShowShadersEdits = QtWidgets.QPushButton(self.groupBox_3)
        self.uiBtnShowShadersEdits.setObjectName("uiBtnShowShadersEdits")
        self.verticalLayout_2.addWidget(self.uiBtnShowShadersEdits)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(ReferencingSample)
        QtCore.QObject.connect(self.uiBtnBrowsePath, QtCore.SIGNAL("clicked()"), ReferencingSample.OnBtnBrowsePathClicked)
        QtCore.QObject.connect(self.uiBtnLoad, QtCore.SIGNAL("clicked()"), ReferencingSample.OnBtnLoadClicked)
        QtCore.QObject.connect(self.uiBtnUnload, QtCore.SIGNAL("clicked()"), ReferencingSample.OnBtnUnloadClicked)
        QtCore.QObject.connect(self.uiBtnReload, QtCore.SIGNAL("clicked()"), ReferencingSample.OnBtnReloadClicked)
        QtCore.QObject.connect(self.uiBtnDelete, QtCore.SIGNAL("clicked()"), ReferencingSample.OnBtnDeleteClicked)
        QtCore.QObject.connect(self.uiBtnInstance, QtCore.SIGNAL("clicked()"), ReferencingSample.OnBtnInstanceClicked)
        QtCore.QObject.connect(self.uiBtnRestore, QtCore.SIGNAL("clicked()"), ReferencingSample.OnBtnRestoreClicked)
        QtCore.QObject.connect(self.uiBtnShowEdits, QtCore.SIGNAL("clicked()"), ReferencingSample.OnBtnShowEditsClicked)
        QtCore.QObject.connect(self.uiBtnShowShadersEdits, QtCore.SIGNAL("clicked()"), ReferencingSample.OnBtnShowShaderEditsClicked)
        QtCore.QObject.connect(self.uiBtnRestoreShaders, QtCore.SIGNAL("clicked()"), ReferencingSample.OnBtnShaderRestoreClicked)
        QtCore.QObject.connect(self.uiBtnBakeShaders, QtCore.SIGNAL("clicked()"), ReferencingSample.OnBtnShaderBakeClicked)
        QtCore.QMetaObject.connectSlotsByName(ReferencingSample)

    def retranslateUi(self, ReferencingSample):
        ReferencingSample.setWindowTitle(QtWidgets.QApplication.translate("ReferencingSample", "Referencing Sample", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("ReferencingSample", "Reference a File", None, -1))
        self.uiBtnBrowsePath.setText(QtWidgets.QApplication.translate("ReferencingSample", "...", None, -1))
        self.uiBtnLoad.setText(QtWidgets.QApplication.translate("ReferencingSample", "Load", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("ReferencingSample", "Namespaces", None, -1))
        self.uiTreeNamespace.headerItem().setText(0, QtWidgets.QApplication.translate("ReferencingSample", "Name", None, -1))
        self.uiTreeNamespace.headerItem().setText(1, QtWidgets.QApplication.translate("ReferencingSample", "Type", None, -1))
        self.uiBtnUnload.setText(QtWidgets.QApplication.translate("ReferencingSample", "Unload", None, -1))
        self.uiBtnReload.setText(QtWidgets.QApplication.translate("ReferencingSample", "Reload", None, -1))
        self.uiBtnDelete.setText(QtWidgets.QApplication.translate("ReferencingSample", "Delete", None, -1))
        self.uiBtnInstance.setText(QtWidgets.QApplication.translate("ReferencingSample", "Instance", None, -1))
        self.uiBtnRestore.setText(QtWidgets.QApplication.translate("ReferencingSample", "Restore to load state", None, -1))
        self.uiBtnRestoreShaders.setText(QtWidgets.QApplication.translate("ReferencingSample", "Restore a Shader Graph", None, -1))
        self.uiBtnBakeShaders.setText(QtWidgets.QApplication.translate("ReferencingSample", "Bake a Shader Graph", None, -1))
        self.uiBtnShowEdits.setText(QtWidgets.QApplication.translate("ReferencingSample", "Show Edits in Popup", None, -1))
        self.uiBtnShowShadersEdits.setText(QtWidgets.QApplication.translate("ReferencingSample", "Shader Edits in Popup", None, -1))
